[workspace]
members = [
    "bins/rpc-v2",
    # enable on demand

    # instead of using wildcard, list independently
    "crates/db",
    "crates/core",
    "crates/indexer",
    "crates/jsonrpc",
    "crates/logger",
    "crates/registry",
    "crates/retirement",
    "crates/types",
    "crates/sync",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.35", features = ["derive", "env"] }
ctrlc = { version = "3.4.7", features = ["termination"] }
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
semver = "1.0.23"
thiserror = "1.0"
tracing = "0.1"
eyre = "0.6"
bincode = "1.3.3"
blake3 = "1.7.0"
crossbeam-channel = "0.5.14"
async-channel = "2.3.1"
async-trait = "0.1.85"
solana-pubkey = { version = "=2.2.1", default-features = false }
solana-sdk = "=2.2.2"
solana-rent = "=2.2.1"
solana-program-runtime = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-svm = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-svm-transaction = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-bpf-loader-program = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-compute-budget = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-compute-budget-instruction = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-runtime = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-runtime-transaction = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-hash = "=2.2.1"
solana-system-program = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-transaction-status = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-transaction-status-client-types = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-account-decoder-client-types = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-account-decoder = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-builtins = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
agave-feature-set = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-transaction-context = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-streamer = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-perf = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-fee = { git = "https://github.com/solayer-labs/agave.git", rev = "8e8488fc141309652c65c56a00492df49416c312" }
solana-sha256-hasher = { version = "=2.2.1" }

axum = "0.8.3"
futures-core = "0.3"
http-body-util = "0.1"
http-body = "1.0"
hyper = { version = "1.6", features = ["full"] }
rustls = "0.23"
tower = "0.4"
klickhouse = { version = "0.13", features = ["default", "bb8"] }
jsonrpsee = { version = "0.24.7", features = [
    "macros",
    "server",
    "ws-client",
] }
hex = "0.4.3"
bs58 = "0.4.0"
base64 = "0.22.1"
zstd = "0.13.2"
metrics = "0.24"
reqwest = { version = "0.12.15", features = ["json", "gzip"] }

infinisvm-db = { path = "./crates/db" }
infinisvm-jsonrpc = { path = "./crates/jsonrpc" }
infinisvm-indexer = { path = "./crates/indexer" }
infinisvm-core = { path = "./crates/core" }
infinisvm-logger = { path = "./crates/logger" }
infinisvm-registry = { path = "./crates/registry" }
infinisvm-types = { path = "crates/types" }
infinisvm-sync = { path = "crates/sync" }
infinisvm-retirement = { path = "./crates/retirement" }

spl-token = "=6.0.0"
spl-token-2022 = "=4.0.0"
hashbrown = "0.14.5"
tikv-jemallocator = "0.6"

tonic = { version = "0.13.1", features = ["transport"] }
prost = "0.13.1"
tonic-build = "0.13.1"
tokio-stream = "0.1.17"

quinn = { version = "0.11.7" }
rcgen = { version = "0.13.0" }
bytes = { version = "1.10.0", features = ["serde"] }
metrics-exporter-prometheus = { version = "0.16" }
prometheus = "0.13.4"
dashmap = { version = "6.1.0" }
paste = "1.0.14"
rand = "0.8.5"
rayon = "1.10.0"
indicatif = "0.18.0"
futures-util = "0.3.31"
tower-http = { version = "0.6.2", features = [
    "cors",
    "compression-full",
    "sensitive-headers",
    "trace",
    "timeout",
] }
pyroscope = { version = "0.5.8", default-features = true }
pyroscope_pprofrs = { version = "0.2.10" }

[profile.release]
debug = true

[patch.crates-io]
hashbrown = { path = "./patches/hashbrown-0.14.5" }
solana-rent = { path = "./patches/solana-rent-2.2.1" }
