[package]
name = "infinisvm-sync"
version = "1.0.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
solana-svm = { workspace = true }
crossbeam-channel = { workspace = true }
infinisvm-types = { workspace = true }
infinisvm-registry = { workspace = true }
infinisvm-logger = { workspace = true }
infinisvm-db = { workspace = true }
dashmap = { workspace = true }
async-trait = { workspace = true }

tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }
rand = { workspace = true }
bincode = { workspace = true }
eyre = { workspace = true }
zstd = { workspace = true }
metrics = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }

# HTTP server dependencies
axum = { workspace = true }
tower = { version = "0.4", features = ["full"] }
tower-http = { workspace = true }
serde = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
rayon = { workspace = true }
indicatif = { workspace = true }
futures-util = { workspace = true }
hashbrown = { workspace = true }
http = "1"
tempfile = "3.10"
walkdir = "2.5.0"
solana-hash = { workspace = true }
solana-transaction-context = { workspace = true }
bytes = { workspace = true }
futures-core = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { version = "0.1.10", features = [
    "client",
    "http1",
    "http2",
    "tokio",
] }

[dev-dependencies]
# Testing dependencies for retry functionality
rand = { workspace = true }
spl-token = { workspace = true }
spl-token-2022 = { workspace = true }

[features]
# Optional features for testing
test-utils = []
e2e = []
