[package]
name = "infinisvm-types"
version = "1.0.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
bincode = { workspace = true }
hashbrown = { workspace = true }
solana-account-decoder-client-types = { workspace = true }
async-trait = { workspace = true }
futures-util = { version = "0.3.14", features = ["sink"] }
futures-core = { workspace = true }
http = "1.0"
bytes = "1.0"
hyper = { workspace = true }
# Enable HTTPS for bincode client
hyper-rustls = { workspace = true }


rustls-pemfile = { workspace = true }
rustls = { workspace = true }
tower = { workspace = true }
http-body-util = { workspace = true }
http-body = { workspace = true }
bb8 = { version = "0.9.0" }
cdrs-tokio = "8.1.6"
cassandra-protocol = "3.3.0"
zstd = "0.12"
metrics = { workspace = true }
regex = "1.1.1"
solana-transaction-context = { workspace = true }
klickhouse = { workspace = true }
solana-hash = { workspace = true }
solana-pubkey = { workspace = true }
solana-svm = { workspace = true }
spl-token = { workspace = true }
spl-token-2022 = { workspace = true }
hex = "0.4"
num-bigint = { version = "0.4.6", features = ["serde"] }

# Build dependencies removed - using bincode for gRPC instead of protobuf